---
- hosts: 
  become: yes
  vars: 
    - newport: 9000
  handlers:
    - name: restart Apache
      service: name=apache2 state=restarted
  tasks: 
    - name: install apache
      apt:
        name: apache2
        state: present 
    - name: start and enable apache
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Change the port to 9000 in port.conf file
      lineinfile: 
        path: /etc/apache2/ports.conf
        regexp: '^Listen \d+'
        line: 'Listen {{ newport }}'
      notify: 
        - restart Apache
    - name: Change the port to 9000 in default.conf file
      lineinfile: 
        path: /etc/apache2/sites-enabled/000-default.conf
        regexp: '^\<VirtualHost \*\:\d+\>'
        line: '<VirtualHost *:{{ newport }}>'
      notify: 
        - restart Apache
